title: "Lalmas Sonia"
email: Soniaalalmas07@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi everyone! have a nice day <3
baseurl: "/" 
url: "https://sunnysunny07.github.io/" 
twitter_username: idonthaveone
github_username:  sunnysunny07

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
